import { AdvancedModulationType } from '../interface/AdvancedModulationType';
import { FilterType } from '../interface/FilterType';
import { Preset } from '../interface/Preset';
import { WaveForm } from '../interface/Waveform';

export const initPreset: Preset = {
    id: 'init',
    name: '- init -',
    options: {
        masterGain: 0.75,
        noise: {
            enabled: false,
            enableRoutingFX: false,
            enableRoutingFilter: false,
            noise: {
                type: 'pink',
            },
            pan: 0,
            envelope: {
                sustain: 1,
                attackCurve: 'linear',
                attack: 0,
                release: 0.1,
                releaseCurve: 'linear',
            },
            volume: 0.1,
        },
        sub: {
            enabled: false,
            oscillator: {
                type: 'sine',
            },
            octave: -2,
            pan: 0,
            waveForm: WaveForm.SINE,
            detune: 0,
            volume: 0.5,
            enableRoutingFX: false,
            enableRoutingFilter: false,
        },
        oscA: {
            enabled: true,
            enableRoutingFX: true,
            enableRoutingFilter: true,
            pan: 0,
            octave: 0,
            spread: 0,
            unison: 1,
            modulationIndex: 0,
            harmonicity: 0.5,
            advancedModulationType: AdvancedModulationType.NONE,
            subModulationType: WaveForm.SQUARE,
            detune: 2,
            waveTablePosition: 0,
            waveForm: WaveForm.CUSTOM,
            oscillator: {
                partials: [0.8, 0.3, 0.2, 0.7, 0.8, 0.3, 1, 0.8],
                type: 'custom',
                phase: 0,
            },
            volume: 0.5,
        },
        oscB: {
            enabled: true,
            enableRoutingFX: true,
            enableRoutingFilter: true,
            pan: 0,
            octave: 0,
            unison: 1,
            modulationIndex: 0,
            harmonicity: 1,
            advancedModulationType: AdvancedModulationType.FAT,
            subModulationType: WaveForm.SQUARE,
            detune: -2,
            waveTablePosition: 0,
            spread: 0,
            waveForm: WaveForm.SAWTOOTH,
            oscillator: {
                type: 'fatsawtooth',
                count: 2,
                phase: 0,
            },
            volume: 0.5,
        },
        metal: {
            enabled: false,
            enableRoutingFX: false,
            enableRoutingFilter: false,
            detune: 0,
            pan: 0,
            harmonicity: 0.5,
            modulationIndex: 0,
            octaves: 3,
            volume: 0.2,
        },
        pluck: {
            enabled: false,
            enableRoutingFX: false,
            enableRoutingFilter: false,
            pan: 0,
            attackNoise: 1,
            dampening: 4000,
            release: 1,
            resonance: 0.7,
            volume: 0.4,
        },
        lfo1: {
            frequency: 0.1,
            min: 1,
            max: 100,
        },
        lfo2: {
            frequency: 0.1,
            min: 1,
            max: 100,
        },
        lfo3: {
            frequency: 0.1,
            min: 1,
            max: 100,
        },
        lfo4: {
            frequency: 0.1,
            min: 1,
            max: 100,
        },
        matrix: [],
        effectRack: {
            volume: 1,
        },
        envelope: {},
        masterFilter: {
            enabled: false,
            volume: 1,
            drive: 0,
            resonance: 1,
            cutoff: 420,
            detune: 0,
            rolloff: -12,
            type: FilterType.LOWPASS,
        },
        voicing: {
            glide: 0.1,
        },
    },
};
